version: "3.9"

services:
  frontend:
    build: .

    ports:
      - '3000:3000'

    volumes:
      - type: bind
        source: .
        target: /app/frontend

    command: sh -c "npm install && npm run build"